<?php
/**
 * @param $route_name
 * @param \Drupal\Core\Routing\RouteMatchInterface $route_match
 * @return string
 */
function module1_help($route_name, \Drupal\Core\Routing\RouteMatchInterface $route_match) {
  switch ($route_name) {

    // Main module help for the block module.
    case 'help.page.module1':
      return '<p>' . t('Blocks are boxes of content rendered into an area, or region, of a web page.
        The default theme Bartik, for example, implements the regions "Sidebar first", "Sidebar second",
        "Featured", "Content", "Header", "Footer", etc., and a block may appear in any one of these areas.
        The <a href=":blocks">blocks administration page</a> provides a drag-and-drop interface for assigning
        a block to a region, and for controlling the order of blocks within regions.', array(
        ':blocks' => \Drupal::url('block.admin_display'),
        )) . '</p>';

    // Help for another path in the block module.
    case 'block.admin_display':
      return '<p>' . t('This page provides a drag-and-drop interface for assigning a block to a region, and for controlling the order of blocks within regions. Since not all themes implement the same regions, or display regions in the same way, blocks are positioned on a per-theme basis. Remember that your changes will not be saved until you click the <em>Save blocks</em> button at the bottom of the page.') . '</p>';
  }
}

function module1_page_attachments(array &$page) {

// Youtube Embed Code
  $meta_robots = [
    '#tag' => 'script',
    '#attributes' => [
      'src' => "https://www.youtube.com/player_api",
      'async' => TRUE,
    ],
  ];
  $page['#attached']['html_head'][] = [$meta_robots, 'youtube_script'];
}

/**
 * Implements hook_cron()
 */
function module1_cron() {
  Drupal::logger('module1')->info('Meeeeeeeeeeeeeeeeensaaaaaaaajeeeeeee');
}



/**
 * Implements hook_theme()
 */
function module1_theme() {
  return array(
    'post_list' => array(
      'variables' => array(
        'title' => 'Lista',
        'items' => array(
          'Variable 1', 'Variable 2', 'Variable 3', 'Variable 4'
        ),
      ),
      'template' => 'list',
    ),
  );
}
